name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Lint Code
      run: go vet -v ./...

    - name: Install Test Runner
      run: go install github.com/mfridman/tparse@latest
    - name: Test
      run: set -o pipefail && go test -json ./... | tparse -all

    - name: Build
      run: go build -v ./...
